dataloader:
  kwargs:
    num_workers: 4
    shuffle: true
    train_batch_size: 1
    valid_batch_size: 1
  name: Dataloader
dataset:
  kwargs:
    augments: null
    data_dir: /home/tony/Documents/IBSR_features_10
    data_split_csv: /home/tony/Documents/Brain_GCN/dataset_split_2d.csv
    train_preprocessings: null
    transforms:
    - name: ToTensor
    valid_preprocessings: null
  name: BrainDataset
logger:
  kwargs:
    dummy_input:
    - 16
    - 1
    - 128
    - 128
  name: KitsSegLogger
losses:
- kwargs:
    weight:
    - 0.25
    - 6.0
    - 0.5
    - 2.0
  name: MyBCELoss
  weight: 1.0
main:
  random_seed: brain
  saved_dir: /home/tony/Documents/Brain_GCN/models/tao_10/train
metrics:
- name: Dice
monitor:
  kwargs:
    early_stop: 0
    mode: min
    saved_freq: 10
    target: Loss
  name: Monitor
net:
  kwargs:
    dropout_rate: 0.3
    n_class: 4
    n_feat: 64
    n_hide: 1024
  name: GCN
optimizer:
  kwargs:
    amsgrad: false
    lr: 0.001
    weight_decay: 0
  name: Adam
trainer:
  kwargs:
    device: cuda:0
    num_epochs: 100
  name: BrainTrainer
